[build]
  command = "npm run prisma:generate && npm run netlify-build"
  publish = "client/dist"
  functions = "netlify/functions"

[build.environment]
  DATABASE_URL = "$DATABASE_URL"
  SHADOW_DATABASE_URL = "$SHADOW_DATABASE_URL"
  ABLY_API_KEY = "$ABLY_API_KEY"

[functions]
  external_node_modules = ["@prisma/client"]
  node_bundler = "esbuild"

[functions.environment]
  DATABASE_URL = "$DATABASE_URL"
  SHADOW_DATABASE_URL = "$SHADOW_DATABASE_URL"
  ABLY_API_KEY = "$ABLY_API_KEY"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000
  publish = "client/dist"
  autoLaunch = true

# Redirect API requests to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Serve the SPA for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200